#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
export MOZ_ENABLE_WAYLAND=1
export MOZ_DBUS_REMOTE=1
export EDITOR=nvim
export GTK_USE_PORTAL=0
# Composer

export PATH="$PATH:$HOME/.config/composer/vendor/bin"

fullscreenshot() {
  FILE=~/Documents/Pictures/"screenshot-$(date +"%Y-%m-%dT%H:%M:%S").png"
  grimshot save screen $FILE
}

screenshot() {
  FILE=~/Documents/Pictures/"screenshot-$(date +"%Y-%m-%dT%H:%M:%S").png"
  grimshot save area $FILE
}