# NVM
[[ -s /usr/share/nvm/init-nvm.sh ]] && source /usr/share/nvm/init-nvm.sh

# Autojump

[[ -s /etc/profile.d/autojump.sh ]] && source /etc/profile.d/autojump.sh

alias vim=nvim;
alias ovim=vim;

# Antigen
source /usr/share/zsh/share/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions
antigen bundle zuxfoucault/colored-man-pages_mod
antigen bundle  zsh-users/zsh-completions
antigen apply

fpath=( ~/.zfunc "${fpath[@]}" )


prompt off
eval "$(starship init zsh)"